services:

  #LARAVEL
  webapp:
    build: ./webapp
    tty: true
    ports:
      - "5173:5173"
    working_dir: /var/www
    volumes:
      - ./webapp/:/var/www
      - ./docker/development/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/development/supervisord/supervisord.conf:/etc/supervisord.conf
      - vendor:/var/www/vendor
      - node_modules:/var/www/node_modules
    env_file:
      - ./webapp/.env
    depends_on:
      - database
      - redis
    networks:
      - app-network

  #PostgreSQL
  database:
    image: pgrouting/pgrouting:17-3.5-main
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=geoglify
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  aisdecoder:
    build: ./aisdecoder
    working_dir: /opt/aisdecoder
    command: 'node index.js'
    environment:
        API_URL: http://webserver:8000/api
        BATCH_SIZE: 100
        FLUSH_INTERVAL: 5000
        AIS_HOST: 153.44.253.27
        AIS_PORT: 5631
    depends_on:
        - webapp
    networks:
        - app-network

  #Nginx
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
      - "8080:8080"
      - "443:443"
    volumes:
      - ./webapp/:/var/www
      - ./docker/development/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - webapp

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

#Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
  vendor:
  node_modules:
