services:
    webapp:
        build: ./webapp
        image: geoglify/webapp
        container_name: gwebapp
        restart: always
        environment:
            PHP_OPCACHE_ENABLE: 1
            PRODUCTION: 0
        ports:
            - 8081:80
            - 8080:8080
            - 5173:5173
        volumes:
            - ./webapp:/var/www/webapp
            - node-modules-data:/var/www/webapp/node_modules
            - vendor-data:/var/www/webapp/vendor
        depends_on:
            - database
            - redis
        healthcheck:
            test: [ 'CMD', 'curl', '-f', 'http://webapp/' ]
            interval: 30s
            timeout: 10s
            retries: 3

    database:
        image: pgrouting/pgrouting:16-3.4-3.6.1
        restart: always
        container_name: gdatabase
        ports:
            - '5432:5432'
        volumes:
            - database-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: geoglify
            POSTGRES_USER: dbadmin
            POSTGRES_PASSWORD: geoglify2024

    redis:
        image: redis:latest
        restart: always
        container_name: gredis
        ports:
            - '6379:6379'
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
            interval: 1s
            timeout: 3s
            retries: 5
        command: [ "redis-server" ]

    aisdecoder:
        build: ./aisdecoder
        container_name: gaisdecoder
        working_dir: /opt/aisdecoder
        command: 'node main.js'
        environment:
            AIS_ANTENNA_HOST: 'ssia-ais.erau.edu'
            AIS_ANTENNA_PORT: 4000
            API_URL: http://webapp/api/ais
        depends_on:
            - webapp
            
    aisstream:
        build: ./aisstream
        container_name: gaisstream
        working_dir: /opt/aisstream
        command: 'node main.js'
        environment:
            NODE_ENV: production
            AISSTREAM_API_KEY: ecee1eee9dd77a3f63c44820715217c00f7f3358
            API_URL: http://webapp/api/ais
            BATCH_SIZE: 1000
            FLUSH_INTERVAL: 1000
        depends_on:
            - webapp

volumes:
    vendor-data:
    node-modules-data:
    database-data:
